tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "outline-variant": "#46464c",
                "on-surface-variant": "#c6c6cc",
                "tertiary-container": "#001312",
                "tertiary-fixed": "#79f6ed",
                "on-secondary-fixed": "#161b2a",
                "surface-container-low": "#191c1f",
                "primary-container": "#001216",
                "surface-container-highest": "#323539",
                "surface-variant": "#323539",
                "inverse-primary": "#006875",
                "inverse-surface": "#e1e2e7",
                "on-surface": "#e1e2e7",
                "on-background": "#e1e2e7",
                "inverse-on-surface": "#2e3134",
                "surface-bright": "#37393d",
                "on-secondary": "#2b303f",
                "on-tertiary-fixed-variant": "#00504c",
                "surface-container-lowest": "#0c0e12",
                "surface-dim": "#111417",
                "error": "#ffb4ab",
                "on-primary-container": "#008999",
                "on-secondary-container": "#b0b4c8",
                "on-tertiary-fixed": "#00201e",
                "on-primary-fixed": "#001f24",
                "secondary-container": "#424657",
                "primary-fixed": "#9cf0ff",
                "primary": "#00daf3",
                "background": "#111417",
                "on-tertiary-container": "#008b84",
                "tertiary-fixed-dim": "#59dad1",
                "secondary-fixed": "#dee2f6",
                "surface-tint": "#00daf3",
                "on-tertiary": "#003734",
                "on-primary-fixed-variant": "#004f58",
                "outline": "#909096",
                "surface-container-high": "#282a2e",
                "tertiary": "#59dad1",
                "on-primary": "#00363d",
                "on-error": "#690005",
                "secondary": "#c2c6da",
                "on-error-container": "#ffdad6",
                "surface": "#111417",
                "surface-container": "#1d2023",
                "primary-fixed-dim": "#00daf3",
                "error-container": "#93000a",
                "on-secondary-fixed-variant": "#424657",
                "secondary-fixed-dim": "#c2c6da"
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
}
